### PR TITLE
added navigation and leaderboard test cases; fixed resource page tests

### PR DESCRIPTION
**Pull request by gang21**

### CODE REVIEW

**Comment by ribru17** [comment]
Can you try rebasing from main? For some reason there are many extraneous commits before "merge from main"

**Comment by ribru17** [comment]
You might also need to look into `got rebase -i`

**Comment by gang21** [comment]
okay i think i did it...

**Comment by ribru17** [comment]
For some reason the commits are still there, now even more :thinking: I think it's because this branch was already used for a PR. Stupid github! I have opened up another PR #87 by cherry picking your commit directly onto main, let me know if any changes were lost

**Pull request closed without merging**
